import React, { Component } from 'react';
import '../../purestack.css';
class Purestack extends Component {


    render() {
        return (
            <form className="screen" novalidate>
                <input id="start" type="checkbox" tabindex="-1" />>
                    <input id="end" type="checkbox" tabindex="-1" />
                <input id="last" type="checkbox" tabindex="-1" />
                <div className="sky">
                    <div></div>
                    <div></div>
                </div>
                <div className="base">
                    <input type="checkbox" tabindex="-1" required />
                    <div className="container horizontal">
                        <div className="block floating horizontal"></div>
                        <div className="block horizontal">
                            <input type="checkbox" tabindex="-1" />
                            <div className="container vertical">
                                <div className="block floating vertical"></div>
                                <div className="block vertical">
                                    <input type="checkbox" tabindex="-1" />
                                    <div className="container horizontal">
                                        <div className="block floating horizontal"></div>
                                        <div className="block horizontal">
                                            <input type="checkbox" tabindex="-1" />
                                            <div className="container vertical">
                                                <div className="block floating vertical"></div>
                                                <div className="block vertical">
                                                    <input type="checkbox" tabindex="-1" />
                                                    <div className="container horizontal">
                                                        <div className="block floating horizontal"></div>
                                                        <div className="block horizontal">
                                                            <input type="checkbox" tabindex="-1" />
                                                            <div className="container vertical">
                                                                <div className="block floating vertical"></div>
                                                                <div className="block vertical">
                                                                    <input type="checkbox" tabindex="-1" />
                                                                    <div className="container horizontal">
                                                                        <div className="block floating horizontal"></div>
                                                                        <div className="block horizontal">
                                                                            <input type="checkbox" tabindex="-1" />
                                                                            <div className="container vertical">
                                                                                <div className="block floating vertical"></div>
                                                                                <div className="block vertical">
                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                    <div className="container horizontal">
                                                                                        <div className="block floating horizontal"></div>
                                                                                        <div className="block horizontal">
                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                            <div className="container vertical">
                                                                                                <div className="block floating vertical"></div>
                                                                                                <div className="block vertical">
                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                    <div className="container horizontal">
                                                                                                        <div className="block floating horizontal"></div>
                                                                                                        <div className="block horizontal">
                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                            <div className="container vertical">
                                                                                                                <div className="block floating vertical"></div>
                                                                                                                <div className="block vertical">
                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                    <div className="container horizontal">
                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                        <div className="block horizontal">
                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                            <div className="container vertical">
                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                <div className="block vertical">
                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                    <div className="container horizontal">
                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                        <div className="block horizontal">
                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                            <div className="container vertical">
                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                <div className="block vertical">
                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="container horizontal">
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="block floating horizontal"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="block horizontal">
                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="last" for="last" tabindex="-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="container vertical">
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="block floating vertical"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="block vertical">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="end horizontal" for="end"></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="end vertical" for="end"></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                </div>
                                                                                                                                                                                            </div>
                                                                                                                                                                                        </div>
                                                                                                                                                                                    </div>
                                                                                                                                                                                </div>
                                                                                                                                                                            </div>
                                                                                                                                                                        </div>
                                                                                                                                                                    </div>
                                                                                                                                                                </div>
                                                                                                                                                            </div>
                                                                                                                                                        </div>
                                                                                                                                                    </div>
                                                                                                                                                </div>
                                                                                                                                            </div>
                                                                                                                                        </div>
                                                                                                                                    </div>
                                                                                                                                </div>
                                                                                                                            </div>
                                                                                                                        </div>
                                                                                                                    </div>
                                                                                                                </div>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="points"></div>
                <label className="start" for="start" tabindex="-1" />
                PURE CSS < br /> STACK

                <button type="reset" tabindex="-1" >
                    CLICK OR TAP < br />
                    TO RESTART
                     </button >
            </form >
        );
    }
}

export default Purestack;